package p5.parte2.comunication;

public enum TipoMensaje {
    CONEXION,
    CONFIRMACION_CONEXION,
    LISTA_USUARIOS,
    CONFIRMACION_LISTA_USUARIOS,
    PEDIR_INFO,
    EMITIR_INFO,
    PREPARADO_CS,
    PREPARADO_SC,
    CERRAR_CONEXION,
    CONFIRMACION_CERRAR_CONEXION,
    CANCELAR_OPCION
}
